### PR TITLE
Fail when committing metadata with incorrect protocol update

### LINKED ISSUE #229: OptimisticTransactionImpl: add extra warning when incorrectly updating the table Protocol
Currently, since DSW 0.3.0 only supports a single protocol version (1, 2), when users try to [change the protocol using metadata.configuration in OptimisticTransaction](https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala#L181), we ignore those changes.

In addition to ignoring those changes, we should log a warning, too.

### PR DESCRIPTION
**Pull request by allisonport-db**
Resolves #229 

Should we throw an error if protocol configuration properties are provided, but they are correct?

### CODE REVIEW

**Comment by scottsand-db** [comment]
> Should we throw an error if protocol configuration properties are provided, but they are correct?

Good question. We shouldn't throw an error in this case.

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 1]
```diff
@@ -263,6 +265,8 @@ private[internal] class OptimisticTransactionImpl(
     if (protocolOpt.isDefined) {
       assert(protocolOpt.get == Protocol(), s"Invalid Protocol ${protocolOpt.get.simpleString}. " +
         s"Currently only Protocol readerVersion 1 and writerVersion 2 is supported.")
+    } else {
+      finalActions = newProtocol.toSeq ++ finalActions
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:269]: doesn't this mean we are double-adding the Protocol action?

```scala
val protocolOpt = finalActions.collectFirst{ case p: Protocol => p } // extract Protocol from finalActions list
...
finalActions = newProtocol.toSeq ++ finalActions // add Protocol back into the finalActions list
```

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 2]
```diff
@@ -231,19 +240,12 @@ private[internal] class OptimisticTransactionImpl(
...
-    // If the metadata has changed, add that to the set of actions
-    finalActions = newMetadata.toSeq ++ finalActions
-
-    val metadataChanges = finalActions.collect { case m: Metadata => m }
-    assert(metadataChanges.length <= 1,
-      "Cannot change the metadata more than once in a transaction.")
-
-    metadataChanges.foreach { m =>
-      verifyNewMetadata(m)
+    newMetadata.foreach{ m =>
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:243]: nit: ` {` (spacing)

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 3]
```diff
@@ -231,19 +240,12 @@ private[internal] class OptimisticTransactionImpl(
       case a: Action => a
     }
 
-    // If the metadata has changed, add that to the set of actions
-    finalActions = newMetadata.toSeq ++ finalActions
-
-    val metadataChanges = finalActions.collect { case m: Metadata => m }
-    assert(metadataChanges.length <= 1,
-      "Cannot change the metadata more than once in a transaction.")
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:239]: since we are removing this assertion, can you please update the scaladoc of this method stating that the caller must ensure no Metadata action is being passed inside of `actions` ?

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 4]
```diff
@@ -165,6 +175,12 @@ private[internal] class OptimisticTransactionImpl(
   }
 
   override def updateMetadata(metadataJ: MetadataJ): Unit = {
+
+    // this Metadata instance was previously added
+    if (newMetadataJ.exists(_ eq metadataJ)) {
+      return
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:181]: so if the user passes in two identical Metadata, we will take the first one only and not throw an exception.

can you add a test for this? (this is a weird case, but a test case makes it explicit)

For example, at first pass I was confused why the test case copied here was passing, but it is because each Metadata() has a different created at time.

```
test("commits shouldn't have more than one Metadata") {
    withTempDir { dir =>
      val log = DeltaLog.forTable(new Configuration(), dir.getCanonicalPath)
      val txn = log.startTransaction()
      val e = intercept[AssertionError] {
        txn.commit(Metadata() :: Metadata() :: Nil, manualUpdate, engineInfo)
      }
      assert(e.getMessage.contains("Cannot change the metadata more than once in a transaction."))
    }
  }
```

Can you also please update this test case name since it is no longer accurate

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 5]
```diff
@@ -180,19 +196,12 @@ private[internal] class OptimisticTransactionImpl(
       SchemaUtils.checkUnenforceableNotNullConstraints(latestMetadata.schema)
     }
 
-    // Remove the protocol version properties
-    val noProtocolVersionConfig = latestMetadata.configuration.filter {
-      case (Protocol.MIN_READER_VERSION_PROP, _) => false
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:185]: can you remind me, what are the consequences of not removing this configuration?

we will still fail later, right? so it won't be committed?

I'm worried that removing this code can mean that we forget to add it back later to Delta Standalone, when we do support multiple protocol versions.

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 6]
```diff
@@ -64,6 +64,8 @@ private[internal] class OptimisticTransactionImpl(
 
   /** Stores the updated metadata (if any) that will result from this txn. */
   private var newMetadata: Option[Metadata] = None
+  /** Stores the updated Java metadata (if any) that will result from this txn. */
+  private var newMetadataJ: Option[MetadataJ] = None
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:68]: This seems very coupled to `newMetadata`. i.e. if one is None, the other should be, too.

also, i think we can get rid of it? inside of `updateMetadata` we already convert MetadataJ to Metadata, right? `var latestMetadata = ConversionUtils.convertMetadataJ(metadataJ)`

Couldn't we just perform the Metadata checks then? Let me know if I'm missing something.

**Review by scottsand-db — CHANGES_REQUESTED** [review]
Left a couple of comments + questions

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 1 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:269]: Err `newProtocol` is only defined if it's a new table (see `updateMetadata`). But this is actually repetitive with 250-262. I think it makes sense to remove the protocol creation in `updateMetadata` and not use `newProtocol` at all.

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 3 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:239]: This assertion is enforced by multiple calls to `updateMetadata` (it will fail the second time it's called.) Re: #229  the issue conversation we decided to accept `Metadata`s in `commit`

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 5 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:185]: We won't fail later. The check is in `verifyNewMetadata`, if we remove these it won't fail. I will update that method to accept the correct protocol configurations, and then that would be where later updates would go for future version support.

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 4 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:181]: So right now it's only accepting the **same** metadata instance (it's checking for reference equality, which is why we're saving the java metadata). Do you think it's more correct to accept equivalent Metadata actions?

For context, this was in theory to accommodate for something like
```
Metadata newMetadata = .....
txn.updateMetadata(newMetadata)
List<Action> actions = .... // generate actions including newMetadata
txn.commit(actions, ....)
```

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 6 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:68]: See below (for reference vs object equality)

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 3 above)
Comment (scottsand-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:239]: Yup, the assertion enforcement is fine, but I'm wondering if it is clear to future developers how it is that at most one metadata can be committed.

Perhaps add a comment to `updateMetadata` that all metadatas (either directly or extracted from commit actions) must go through that method?

But if you think it's fine, then SGTM.

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 4 above)
Comment (scottsand-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:181]: I see. I guess my question is, why check for reference equality instead value equality? If two different Metadata actions are value-equivalent, then the same JSON will be written to the delta log, which is all that matters.

So I think that value-equality is fine here.

And this will still work for your code example given above

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 5 above)
Comment (scottsand-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:185]: > that would be where later updates would go for future version support

But why shift this check from here to that function? If Delta OSS and DBR both perform similar checks in this method, what do we gain from moving checks there?

**Review by scottsand-db — CHANGES_REQUESTED** [review]
Responded to comments + asked some questions

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 5 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:185]: This isn't a check though, it's filtering out those properties. The check has always been in `verifyNewMetadata` and our issue with not failing was because we were filtering out those properties before. In delta OSS all metadata goes through `verifyNewMetadata` in both `prepareCommit` and `updateMetadata`

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 4 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:181]: I think that's fair then sg

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala (hunk 3 above)
Comment (allisonport-db) [reply standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:239]: I'll add a comment

File: standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala [hunk 7]
```diff
@@ -164,30 +172,39 @@ private[internal] class OptimisticTransactionImpl(
...
   }
 
+  /**
+   * All [[Metadata]] actions must go through this function, and be added to the committed actions
+   * via `newMetadata` (they shouldn't ever be passed into `prepareCommit`.)
+   * This function enforces:
+   * - At most one unique [[Metadata]] is committed in a single transaction.
+   * - If this is the first commit, the committed metadata configuration includes global Delta
+   *   configuration defaults.
+   * - Checks for unenforceable NOT NULL constraints in the table schema.
```
Comment (scottsand-db) [inline standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala:182]: Do you mean to have 3 levels of indentation?
```
* - ...
*  - ...
*    - ...
```

**Review by scottsand-db — APPROVED** [review]
LGTM with 1 indentation nit / comment
